# Generated by Django 5.1.3 on 2025-03-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
