# Generated by Django 5.1.3 on 2025-03-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_ispublic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='isPublic',
            new_name='is_public',
        ),
    ]
